// Auto-generated content file
// Do not edit manually - this file is generated by scripts/build-content.js

export interface MarkdownContent {
  content: string
  data: {
    title?: string
    description?: string
    [key: string]: unknown
  }
}

export interface GuideItem {
  slug: string
  title: string
  description: string
  content: string
  data: {
    [key: string]: unknown
  }
}

export const STATIC_GUIDES: GuideItem[] = [
  {
    "slug": "afk-pond",
    "title": "Afk Pond",
    "description": "Guide documentation",
    "content": "<p>We understand that sometimes you need to go AFK (Away From Keyboard). At our AFK Pond, you can do so while still earning some nice rewards for your time.</p>\n<h3>How it Works:</h3>\n<p>Simply go to <code>/warp afk</code> and stand in the pond. That's it! As long as you remain in the pond, you'll accumulate rewards.</p>\n<h3>Rewards:</h3>\n<ul>\n<li><strong>15 minutes</strong> = 2 Coins</li>\n<li><strong>1 hour</strong> = 1 Common Crate Key</li>\n</ul>\n<p>It's an easy way to earn some extra currency and keys while you're busy.</p>\n",
    "data": "title:\"AFK Pond\" description:\"Need to step away for a bit? Our AFK Pond rewards you for staying online, even when you're not actively playing.\""
  },
  {
    "slug": "arena",
    "title": "Arena",
    "description": "Guide documentation",
    "content": "<p>Ready to test your combat skills? The Arena is where you can engage in <strong>Player vs. Player (PvP)</strong> combat without any risk to your items in the normal survival world. It's the perfect place to practice your fighting skills and have some fun.</p>\n<h3>How to Enter the Arena:</h3>\n<p>Use the command <code>/warp arena</code> to teleport directly to the PvP zone.</p>\n<h3>Supply Crates:</h3>\n<p>To make things more interesting, a new batch of <strong>Supply Crates</strong> will spawn in the arena every hour. These crates are filled with valuable loot, but you'll have to be quick and fight off other players to get to them first!</p>\n",
    "data": "title:\"Arena\" description:\"The Arena is the designated zone for PvP. Fight other players, test your strength, and loot valuable Supply Crates.\""
  },
  {
    "slug": "auction",
    "title": "Auction",
    "description": "Guide documentation",
    "content": "<p>The Auction House is where you can trade with other players. It's the best place to find rare items that you can't buy in the regular shop, or to sell your own unique treasures for a great price.</p>\n<h3>How to Use the Auction House:</h3>\n<ul>\n<li><strong>To View Auctions</strong>: Simply use the command <code>/ah</code> or <code>/auction</code> to open the menu and browse what other players are selling.</li>\n<li><strong>To Sell an Item</strong>: Hold the item you want to sell in your hand and use the command:\n<code>/auction sell &#x3C;price></code></li>\n</ul>\n<p>This is the safest way to trade with other players, as the server handles the transaction for you.</p>\n",
    "data": "title:\"Auction House\" description:\"The Auction House is the player-driven marketplace. Buy and sell rare items, gear, and more in a safe and easy way.\""
  },
  {
    "slug": "basic-commands",
    "title": "Basic Commands",
    "description": "Guide documentation",
    "content": "<p>Think of these as your essential toolkit for getting around and managing your gameplay.</p>\n<ul>\n<li><code>/worlds</code> ➜ Opens a menu to easily travel between the different worlds, like Survival, the Nether, and the End.</li>\n<li><code>/spawn</code> ➜ Instantly teleports you back to the server's main spawn point.</li>\n<li><code>/sethome</code> ➜ Sets a \"home\" point at your current location. This is your personal teleport spot!</li>\n<li><code>/home</code> ➜ Teleports you to the location you've set with <code>/sethome</code>.</li>\n<li><code>/delhome</code> ➜ Deletes a home you've previously set.</li>\n<li><code>/pay &#x3C;player> &#x3C;amount></code> ➜ Safely transfer money to another player.</li>\n<li><code>/tpa &#x3C;player></code> ➜ Request to teleport to another player's location.</li>\n<li><code>/tpaccept</code> ➜ Accept a teleport request from another player.</li>\n<li><code>/tpdeny</code> ➜ Deny a teleport request.</li>\n<li><code>/warps</code> ➜ Opens a menu of important public locations you can teleport to instantly.</li>\n</ul>\n",
    "data": "title:\"Basic Commands\" description:\"Here are the essential commands that will help you navigate the server and interact with the world. Every player should get familiar with these!\""
  },
  {
    "slug": "chat-games",
    "title": "Chat Games",
    "description": "Guide documentation",
    "content": "<p>Every so often, a game will pop up in the server chat. These are fun, simple challenges where the goal is to be the fastest person to type the correct answer.</p>\n<h3>How Chat Games Work:</h3>\n<ul>\n<li>A question or challenge will appear automatically in the chat (e.g., unscramble a word, solve a math problem).</li>\n<li>The first person to type the correct answer into chat wins a small prize, like money or a crate key.</li>\n</ul>\n<p>It's a fun way to pass the time and earn some extra rewards!</p>\n",
    "data": "title:\"Chat Games\" description:\"Keep an eye on the chat for fun and fast-paced games! Be the first to answer correctly to win a prize.\""
  },
  {
    "slug": "claiming",
    "title": "Claiming",
    "description": "Guide documentation",
    "content": "<h3>Protect Your Hard Work!</h3>\n<p>Found the perfect spot for your base? Great! The next step is to <strong>claim the land</strong> to protect it. Claiming an area prevents other players from placing or breaking blocks, opening your chests, or using your items. It's your own private space!</p>\n<h3>How To Claim Land:</h3>\n<p>Claiming is easy and uses a <strong>Golden Shovel</strong>.</p>\n<ol>\n<li>Get a Golden Shovel (you can craft one or use one from a kit).</li>\n<li>Go to one corner of the area you want to claim and <strong>right-click a block</strong> with the Golden Shovel.</li>\n<li>Walk to the opposite corner of the area.</li>\n<li><strong>Right-click another block</strong> there. Your claim is now created!</li>\n</ol>\n<p>You can see your claimed areas and how many claim blocks you have left by holding your shovel. You get more claim blocks automatically just by playing on the server!</p>\n",
    "data": "title:\"Claiming\" description:\"Learn how to protect your builds and items by claiming land. This is the most important step to keeping your base safe!\""
  },
  {
    "slug": "coins",
    "title": "Coins",
    "description": "Guide documentation",
    "content": "<p>Coins are a premium currency that unlock a whole new range of cool items and perks. While regular money is for survival needs, Coins are for showing off your style!</p>\n<h3>How to Get Coins:</h3>\n<p>Coins are more valuable and harder to get than money. You can earn them by:</p>\n<ul>\n<li><strong>Leveling Up</strong>: You'll receive Coins as a reward for reaching new levels.</li>\n<li><strong><code>/rewards</code></strong>: Claim your daily and weekly rewards for a chance at some Coins.</li>\n<li><strong><code>/afk</code></strong>: Hang out at our AFK Pond to earn Coins while you're away.</li>\n<li><strong>Server Store</strong>: You can also purchase Coins from our webstore to support the server.</li>\n</ul>\n<h3>The Coinshop</h3>\n<p>Use the <code>/coinshop</code> command to browse all the exclusive items you can buy with your Coins, including <strong>Cosmetics</strong>, <strong>ToolSkins</strong>, and more!</p>\n",
    "data": "title:\"Coins\" description:\"Coins are our server's special currency. Use them to buy unique cosmetic items and perks that you can't get with regular money.\""
  },
  {
    "slug": "cosmetics",
    "title": "Cosmetics",
    "description": "Guide documentation",
    "content": "<p>Want to add a little extra flair to your character? Our cosmetics system allows you to equip cool visual effects, particles, and other fun items to make your character unique.</p>\n<h3>How to Get Cosmetics:</h3>\n<p>You can purchase a wide variety of cosmetics using <strong>Coins</strong> in the <code>/coinshop</code>. These items are purely for looks and do not provide any gameplay advantage, so you can express yourself without worrying about game balance.</p>\n<p>Browse the shop to find the perfect cosmetic to match your style!</p>\n",
    "data": "title:\"Cosmetics\" description:\"Stand out from the crowd with unique cosmetic items! Cosmetics are a fun way to personalize your appearance on the server.\""
  },
  {
    "slug": "crates",
    "title": "Crates",
    "description": "Guide documentation",
    "content": "<p>Crates are a fun way to get your hands on some of the best items on the server. Each crate requires a <strong>key</strong> to open, and each key corresponds to a different type of crate with different potential loot.</p>\n<h3>How to Open Crates:</h3>\n<ol>\n<li>Get a Crate Key by voting, from rewards, or from the server store.</li>\n<li>Go to the <strong>Crate Area</strong> at <code>/warp crates</code>.</li>\n<li>Right-click the crate that matches your key.</li>\n<li>Watch the roll and see what amazing prize you've won!</li>\n</ol>\n<h3>Available Crates:</h3>\n<p>We have several tiers of crates, each better than the last:</p>\n<ul>\n<li><strong>Vote Crate</strong></li>\n<li><strong>Common Crate</strong></li>\n<li><strong>Rare Crate</strong></li>\n<li><strong>Epic Crate</strong></li>\n<li><strong>Superior Crate</strong></li>\n</ul>\n",
    "data": "title:\"Crates\" description:\"Use Crate Keys to open crates for a chance at unique and amazing rewards. It's like opening a treasure chest!\""
  },
  {
    "slug": "daily-quests",
    "title": "Daily Quests",
    "description": "Guide documentation",
    "content": "<p>Daily Quests are a special set of tasks that reset every single day. They are one of the most efficient and rewarding ways to gain <strong>Level XP</strong> on the server.</p>\n<h3>How Daily Quests Work:</h3>\n<ul>\n<li>Use the <code>/quests</code> command to see your available daily quests.</li>\n<li>Complete the objectives, which could be anything from mining certain blocks to catching fish.</li>\n<li>Once completed, you'll receive a large amount of Level XP!</li>\n</ul>\n<p>Making a habit of completing your daily quests is the fastest way to level up and unlock new perks!</p>\n",
    "data": "title:\"Daily Quests\" description:\"Daily Quests are a fantastic way to earn Level XP every day. Make sure to complete them to maximize your progress!\""
  },
  {
    "slug": "donator-ranks",
    "title": "Donator Ranks",
    "description": "Guide documentation",
    "content": "<p>Our server is free to play, but if you wish to support our community and development, you can purchase a donator rank. These ranks come with a variety of special perks and commands as a thank you for your support.</p>\n<h3>Available Ranks:</h3>\n<ul>\n<li><strong>Knight Rank</strong></li>\n<li><strong>Lord Rank</strong></li>\n<li><strong>Paladin Rank</strong></li>\n<li><strong>Duke Rank</strong></li>\n<li><strong>King Rank</strong></li>\n</ul>\n<p>Each rank offers progressively better perks, such as more <code>/sethome</code> slots, access to exclusive kits, and much more.</p>\n<p>To see the full list of perks for each rank, you can visit the <strong>rank NPCs at spawn</strong> or check out our webstore.</p>\n",
    "data": "title:\"Donator Ranks\" description:\"Support the server and get amazing perks by purchasing a donator rank! Ranks are the best way to enhance your gameplay experience.\""
  },
  {
    "slug": "economy",
    "title": "Economy",
    "description": "Guide documentation",
    "content": "<p>Money is a central part of our server, allowing you to buy, sell, and trade with other players. A healthy bank balance will open up many new opportunities for you!</p>\n<h3>How to Earn Money:</h3>\n<p>There are many ways to build your fortune:</p>\n<ul>\n<li><strong><code>/shop</code></strong>: The most reliable way to make money. Sell the resources you gather, like crops, ores, and wood, for instant cash.</li>\n<li><strong><code>/jobs</code></strong>: Join a job to get paid for doing the things you already do, like mining, fishing, or building.</li>\n<li><strong><code>/auction</code></strong>: Sell rare and valuable items directly to other players in the auction house.</li>\n<li><strong>Leveling Up</strong>: You get a cash reward every time you level up!</li>\n</ul>\n<h3>How to Spend Money:</h3>\n<p>Once you have money, you can use it for:</p>\n<ul>\n<li><strong>Buying from players</strong>: Purchase items from the <code>/auction</code> or trade directly with others.</li>\n<li><strong><code>/lottery</code></strong>: Feeling lucky? Buy a lottery ticket for a chance to win the grand prize!</li>\n<li><strong>Factories</strong>: Invest in factories to produce valuable materials automatically.</li>\n</ul>\n",
    "data": "title:\"Economy\" description:\"Learn how money works on the server and all the ways you can earn and spend it. Becoming wealthy is a fun goal for any player!\""
  },
  {
    "slug": "emojis",
    "title": "Emojis",
    "description": "Guide documentation",
    "content": "<p>Sometimes, words just aren't enough. Our server supports a wide range of custom emojis that you can use in chat to show exactly how you're feeling.</p>\n<h3>How to Use Emojis:</h3>\n<p>To see a full list of all available emojis and their codes, simply use the command:</p>\n<p><code>/emojis</code></p>\n<p>From there, you can copy and paste the emoji codes directly into your chat messages. Have fun with them!</p>\n",
    "data": "title:\"Emojis\" description:\"Express yourself in chat with our custom emojis! It's a fun and easy way to add more personality to your messages.\""
  },
  {
    "slug": "factories",
    "title": "Factories",
    "description": "Guide documentation",
    "content": "<p>Factories introduce a whole new way to get materials on the server. Instead of gathering everything by hand, you can invest in factories that will produce certain materials for you automatically over time.</p>\n<h3>How Factories Work:</h3>\n<p>Use the factories menu to browse the different types of factories you can build. Each factory requires an initial investment of money and resources, but once it's running, it will generate valuable items for you to collect.</p>\n<p>This is an advanced feature that is perfect for players who want to dive deep into our server's economy.</p>\n",
    "data": "title:\"Factories\" description:\"Factories are a unique way to generate materials automatically. Invest in a factory to create a passive income stream.\""
  },
  {
    "slug": "getting-started",
    "title": "Getting Started",
    "description": "Guide documentation",
    "content": "<h3>Welcome to the Server!</h3>\n<p>We're so excited to have you join our community! Your epic survival adventure starts now. Follow these simple steps to get going:</p>\n<ol>\n<li>\n<p><strong>Teleport to the Survival World</strong>\nTo begin, you'll want to head to our main survival world. You can get to a random spot in the wild by using the command <code>/rtp</code>. This will ensure you have plenty of space to yourself.</p>\n</li>\n<li>\n<p><strong>Gather Resources &#x26; Build Your Base</strong>\nJust like classic survival, you'll need to gather resources like wood, stone, and food. Once you've found the perfect spot, you can start building your first home!</p>\n</li>\n<li>\n<p><strong>Claim Your Land</strong>\nTo protect your creations, you must <strong>claim your land</strong>. This prevents other players from building or breaking blocks in your area. Check out our <code>Claiming</code> guide for a simple walkthrough on how to do this.</p>\n</li>\n</ol>\n<h3>Get a Head Start!</h3>\n<p>To help you on your journey, we offer some free rewards:</p>\n<ul>\n<li>Use the <code>/rewards</code> command to get free items every hour, day, and week!</li>\n<li>Don't forget to use your free <strong>Crate Keys</strong> at <code>/warp crates</code>. You might get something amazing!</li>\n</ul>\n",
    "data": "title:\"Getting Started\" description:\"Your adventure begins here! Follow these steps to jump right into the action and make the most of your time on the server.\""
  },
  {
    "slug": "homes",
    "title": "Homes",
    "description": "Guide documentation",
    "content": "<p>Homes are one of the most useful commands on the server. A home is a personal teleport point that you can set anywhere you like, allowing you to return to that exact spot instantly.</p>\n<h3>How to Use Homes:</h3>\n<ul>\n<li><code>/sethome &#x3C;name></code> ➜ Creates a home with a specific name at your current location.</li>\n<li><code>/home &#x3C;name></code> ➜ Teleports you to the home you specified.</li>\n<li><code>/delhome &#x3C;name></code> ➜ Deletes a home.</li>\n</ul>\n<h3>Home Limits:</h3>\n<p>By default, all players can set <strong>2 homes</strong>. You can unlock the ability to set more homes by <strong>leveling up</strong> on the server or by purchasing a donator rank.</p>\n",
    "data": "title:\"Homes\" description:\"Set personal teleport points called homes to get back to your base instantly from anywhere in the world.\""
  },
  {
    "slug": "jobs",
    "title": "Jobs",
    "description": "Guide documentation",
    "content": "<p>Joining a job is one of the best ways to ensure you have a steady flow of cash. With 12 different jobs available, you can get paid for doing the tasks you enjoy most.</p>\n<h3>How Jobs Work:</h3>\n<ol>\n<li>Use the <code>/jobs</code> command to browse the available jobs.</li>\n<li>Choose a job that fits your playstyle (e.g., Miner, Farmer, Hunter, Builder).</li>\n<li>That's it! You'll now automatically earn money as you perform tasks related to your job.</li>\n</ol>\n<h3>The Pointshop</h3>\n<p>As you work, you won't just earn money—you'll also get <strong>Job Points</strong>. These points can be spent in the <code>/pointshop</code> on valuable items and special rewards that you can't get anywhere else!</p>\n",
    "data": "title:\"Jobs\" description:\"Join a job to earn a reliable income and special points just for playing the game. It's a great way to make money while you have fun!\""
  },
  {
    "slug": "king-of-the-hill",
    "title": "King Of The Hill",
    "description": "Guide documentation",
    "content": "<p><strong>King Of The Hill (KOTH)</strong> is an automated event where players battle to capture and hold a specific area in the arena. It's a true test of strength and strategy.</p>\n<h3>How KOTH Works:</h3>\n<ol>\n<li>An announcement will be made in chat when a KOTH event is about to begin.</li>\n<li>Head to the designated KOTH area at <code>/warp arena</code>.</li>\n<li>Stand in the capture zone to start capturing it. Be prepared to fight off other players who want to claim it for themselves!</li>\n<li>The player who holds the point for the required amount of time wins the event and receives amazing rewards!</li>\n</ol>\n",
    "data": "title:\"King Of The Hill (KOTH)\" description:\"KOTH is a server-wide PvP event where you must fight to control a specific point and become the King. Glory and epic rewards await the winner!\""
  },
  {
    "slug": "kits",
    "title": "Kits",
    "description": "Guide documentation",
    "content": "<p>Kits are a quick way to get a full set of gear and items. They are on a cooldown, so you can claim them periodically to restock.</p>\n<h3>How to Use Kits:</h3>\n<p>Use the <code>/kits</code> command to see all the kits available to you. From there, you can claim any kit that isn't on cooldown.</p>\n<h3>Types of Kits:</h3>\n<ul>\n<li><strong>Starter Kits</strong>: These kits are available to all players and provide essential items to help you get started, like basic tools, food, and armor.</li>\n<li><strong>Ranked Kits</strong>: These are exclusive, more powerful kits that are only available to players who have purchased a donator rank. The higher the rank, the better the kit!</li>\n</ul>\n",
    "data": "title:\"Kits\" description:\"Kits give you a bundle of useful items to help you on your adventure. There are kits available for everyone, plus exclusive kits for donator ranks.\""
  },
  {
    "slug": "leaderboards",
    "title": "Leaderboards",
    "description": "Guide documentation",
    "content": "<p>Are you a competitive player? The leaderboards are where you can see who's on top. We track a wide variety of stats, so you can see who has the most money, the most kills, and much more.</p>\n<h3>How to View Leaderboards:</h3>\n<ul>\n<li>Use the <code>/leaderboards</code> command to open the main menu.</li>\n</ul>\n<p>Climb the ranks and get your name on the board!</p>\n",
    "data": "title:\"Leaderboards\" description:\"See how you stack up against the competition! Our leaderboards track the top players in various categories.\""
  },
  {
    "slug": "levels",
    "title": "Levels",
    "description": "Guide documentation",
    "content": "<p>Levels are a core part of your progression on the server. Nearly everything you do, from mining and building to fighting monsters, will earn you <strong>Level XP</strong>. As you gain XP, you will level up!</p>\n<h3>How Leveling Works:</h3>\n<ul>\n<li><strong>Gain XP</strong>: You get Level XP automatically just by being online and playing.</li>\n<li><strong>Level Up</strong>: When your XP bar is full, you'll advance to the next level.</li>\n</ul>\n<h3>Perks of Leveling Up:</h3>\n<p>Each time you level up, you'll receive great rewards, such as:</p>\n<ul>\n<li><strong>Money and Coins</strong></li>\n<li><strong>More <code>/sethome</code> slots</strong></li>\n<li><strong>Access to new commands and perks</strong></li>\n</ul>\n<p>Leveling is our way of rewarding you for being an active member of our community!</p>\n",
    "data": "title:\"Levels\" description:\"Our server has a leveling system that rewards you for your playtime. The more you play, the more perks you unlock!\""
  },
  {
    "slug": "lottery",
    "title": "Lottery",
    "description": "Guide documentation",
    "content": "<p>Do you have some extra cash and a desire for a huge payout? The lottery is the place for you!</p>\n<h3>How the Lottery Works:</h3>\n<ul>\n<li><strong>Buy a Ticket</strong>: Use the <code>/lottery</code> command to buy one or more tickets for the current draw.</li>\n<li><strong>Wait for the Draw</strong>: The lottery is drawn automatically every day. The more tickets that are bought by all players, the bigger the final prize pot gets!</li>\n<li><strong>Win Big</strong>: If your ticket is chosen, you win the entire pot! It's a thrilling way to potentially become one of the richest players on the server overnight.</li>\n</ul>\n",
    "data": "title:\"Lottery\" description:\"Feeling lucky? Enter the lottery for a chance to win a massive cash prize! It's a high-risk, high-reward way to get rich quick.\""
  },
  {
    "slug": "playerwarps",
    "title": "Playerwarps",
    "description": "Guide documentation",
    "content": "<p>Player Warps allow you to set up your own public teleport point that any other player on the server can use. This is perfect for creating player-run shops, public farms, or just showing off a cool build.</p>\n<h3>How to Create a Player Warp:</h3>\n<ol>\n<li>Stand in the exact spot where you want players to arrive.</li>\n<li>Use the command <code>/pw set &#x3C;name></code>.</li>\n</ol>\n<p>That's it! Your warp is now active and will appear in the Player Warps menu for everyone to see. You can manage your warps with other <code>/pw</code> commands.</p>\n",
    "data": "title:\"Player Warps\" description:\"Create your own public warp to let other players visit your shop, base, or build. It's a great way to show off your creations!\""
  },
  {
    "slug": "quests",
    "title": "Quests",
    "description": "Guide documentation",
    "content": "<p>If you're ever looking for something to do, our questing system is the perfect place to start. We have a huge variety of tasks, from simple gathering quests to more complex challenges.</p>\n<h3>How to Start Questing:</h3>\n<p>Use the <code>/quests</code> command to open the main quest menu. Here, you can browse through hundreds of available quests, track your progress, and claim your rewards.</p>\n<p>With <strong>500+ quests</strong>, they are a great way to explore all the features the server has to offer while earning some great loot along the way!</p>\n",
    "data": "title:\"Quests\" description:\"With over 500 quests, you will never run out of things to do! Quests are a fun way to challenge yourself and earn rewards.\""
  },
  {
    "slug": "rewards",
    "title": "Rewards",
    "description": "Guide documentation",
    "content": "<p>We believe in rewarding our players just for being a part of our community. That's why we have a simple rewards system that gives you free stuff just for playing!</p>\n<h3>How to Claim Rewards:</h3>\n<p>Use the <code>/rewards</code> command to open the rewards menu. Here you can claim all your available rewards.</p>\n<h3>Available Rewards:</h3>\n<ul>\n<li><strong>Hourly Rewards</strong>: Claim a small reward every single hour.</li>\n<li><strong>Daily Rewards</strong>: Log in every day to claim a bigger and better reward.</li>\n<li><strong>Weekly Rewards</strong>: The best of them all! Log in every week to claim a fantastic prize.</li>\n</ul>\n<p>Remember to claim your rewards regularly to make the most of them!</p>\n",
    "data": "title:\"Rewards\" description:\"Get rewarded just for playing on the server! Claim your free rewards to get a boost of items, money, and keys.\""
  },
  {
    "slug": "rules",
    "title": "Rules",
    "description": "Guide documentation",
    "content": "<p>To make sure our server is a fun, safe, and fair place for everyone, we have a set of rules that all players are expected to follow. Ignorance of the rules is not an excuse for breaking them.</p>\n<p>Our rules are based on common sense, but here are the key points:</p>\n<ol>\n<li><strong>Be Respectful</strong>: No harassment, hate speech, or excessive toxicity towards any player.</li>\n<li><strong>No Cheating or Hacking</strong>: Using any kind of hacked client, x-ray, or exploits is strictly forbidden.</li>\n<li><strong>No Griefing or Stealing</strong>: Do not destroy or steal from another player's claimed land.</li>\n<li><strong>No Spamming or Advertising</strong>: Do not spam the chat or advertise other servers.</li>\n</ol>\n<p>For a full, detailed list of the rules, please visit the rules board at spawn.</p>\n",
    "data": "title:\"Rules\" description:\"To ensure a fun and fair environment for everyone, we have a set of rules that all players must follow. Please read them carefully.\""
  },
  {
    "slug": "shop",
    "title": "Shop",
    "description": "Guide documentation",
    "content": "<p>The shop is the most straightforward way to make money on the server. By selling the items you gather, you can build a steady income to fund all your projects.</p>\n<h3>How to Use the Shop:</h3>\n<p>Simply use the <code>/shop</code> command to open the shop menu. From there, you can browse different categories and see the current prices for all sellable items.</p>\n<h3>What Sells Best?</h3>\n<p>While many items can be sold, focusing on these resources is a great strategy for making money:</p>\n<ul>\n<li><strong>Farming Resources</strong>: Crops like wheat, carrots, potatoes, and sugarcane are always in demand.</li>\n<li><strong>Mining Resources</strong>: Ores like iron, gold, and diamonds, as well as other materials like cobblestone, are great sellers.</li>\n</ul>\n",
    "data": "title:\"Shop\" description:\"The server shop is your go-to place for selling resources to earn money. It's the foundation of our economy!\""
  },
  {
    "slug": "skills",
    "title": "Skills",
    "description": "Guide documentation",
    "content": "<p>Beyond your main player level, you can also train a variety of <strong>skills</strong>. This system rewards you for specializing in certain tasks. The more you practice a skill, the higher its level will become, unlocking special abilities and perks along the way.</p>\n<h3>How Skills Work:</h3>\n<p>When you perform certain actions, you gain skill XP. For example:</p>\n<ul>\n<li><strong>Mining</strong>: Breaking ores and stone levels up your Mining skill.</li>\n<li><strong>Farming</strong>: Harvesting crops improves your Farming skill.</li>\n<li><strong>Running</strong>: Simply moving around the world will increase your Running skill over time.</li>\n</ul>\n<p>As your skills level up, you might unlock passive boosts, special abilities, or other cool perks related to that skill!</p>\n",
    "data": "title:\"Skills\" description:\"Improve your character's abilities by leveling up your skills. The more you do a task, the better you get at it!\""
  },
  {
    "slug": "tags",
    "title": "Tags",
    "description": "Guide documentation",
    "content": "<p>Tags are a great way to personalize your chat identity. A tag is a small icon that appears right before your name in chat, allowing you to show off your personality or achievements.</p>\n<h3>How to Get Tags:</h3>\n<p>You can browse and obtain tags from a variety of sources, including:</p>\n<ul>\n<li>The <code>/coinshop</code></li>\n<li>Crates</li>\n<li>Level-up rewards</li>\n</ul>\n<p>With over 100 different tags to choose from, you're sure to find one that you love!</p>\n",
    "data": "title:\"Tags\" description:\"Add a special icon next to your name with a chat tag. With over 100 to choose from, you can find the perfect one to represent you.\""
  },
  {
    "slug": "teams",
    "title": "Teams",
    "description": "Guide documentation",
    "content": "<p>Why play alone when you can team up? Our server allows you to create and join teams to collaborate with other players.</p>\n<h3>How to Use Teams:</h3>\n<ul>\n<li><code>/team create &#x3C;name></code> ➜ Create a new team.</li>\n<li><code>/team invite &#x3C;player></code> ➜ Invite a player to your team.</li>\n<li><code>/team join &#x3C;team></code> ➜ Join a team you've been invited to.</li>\n<li><code>/team leave</code> ➜ Leave your current team.</li>\n</ul>\n<h3>Team Perks:</h3>\n<p>Being on a team gives you access to great features:</p>\n<ul>\n<li><strong>Team Chat</strong>: A private chat channel only for your team members.</li>\n<li><strong>Team Homes</strong>: Shared <code>/sethome</code> locations that all team members can teleport to.</li>\n<li><strong>Team Balance</strong>: A shared bank account for the team.</li>\n<li><strong>Team Ranks &#x26; Upgrades</strong>: Promote members within your team and unlock team-wide upgrades.</li>\n</ul>\n",
    "data": "title:\"Teams\" description:\"Team up with your friends to share resources, homes, and a private chat. Working together makes the adventure even more fun!\""
  },
  {
    "slug": "toolskins",
    "title": "Toolskins",
    "description": "Guide documentation",
    "content": "<p>Tired of your diamond sword looking the same as everyone else's? With ToolSkins, you can apply a new, custom look to your favorite tools and weapons.</p>\n<h3>How ToolSkins Work:</h3>\n<ol>\n<li><strong>Obtain a Skin</strong>: You can get ToolSkins from the <code>/coinshop</code>, from Crates, or as a reward for leveling up.</li>\n<li><strong>Apply the Skin</strong>: Use the ToolSkins menu to apply a skin to an item in your inventory.</li>\n</ol>\n<p>This is a purely cosmetic change, so you can look cool without affecting the stats of your tools. Mix and match to create the perfect look!</p>\n",
    "data": "title:\"ToolSkins\" description:\"Customize your tools and weapons with unique skins! This feature lets you change the appearance of your items, similar to skins in games like CS:GO.\""
  },
  {
    "slug": "warps",
    "title": "Warps",
    "description": "Guide documentation",
    "content": "<p>Warps are preset public teleport points that take you to all the important areas on the server. They are the fastest way to get to key locations.</p>\n<h3>How to Use Warps:</h3>\n<p>Use the <code>/warps</code> command to open a menu of all available warps. Simply click on the one you want to visit.</p>\n<h3>Key Warps:</h3>\n<ul>\n<li><strong>Spawn</strong>: The central hub of the server where you first log in.</li>\n<li><strong>Crates</strong>: The area where you can open your Crate Keys for rewards.</li>\n<li><strong>Arena</strong>: The designated zone for PvP combat.</li>\n<li><strong>Worlds</strong>: A hub for traveling between the different worlds (Survival, Nether, etc.).</li>\n</ul>\n",
    "data": "title:\"Warps\" description:\"Warps are instant teleports to the most important locations on the server. Use them to get around quickly and easily.\""
  },
  {
    "slug": "worlds",
    "title": "Worlds",
    "description": "Guide documentation",
    "content": "<p>Our server features several distinct worlds for you to explore, build, and conquer. You can travel between them using the <code>/worlds</code> command.</p>\n<h3>Our Worlds:</h3>\n<ul>\n<li>\n<p><strong>Survival World (30k x 30k)</strong>\nThis is the main world where you will build your base, team up with friends, and live your survival adventure. Its massive size means there's plenty of room for everyone!</p>\n</li>\n<li>\n<p><strong>Nether World (10k x 10k)</strong>\nThe classic realm of fire and danger. Travel here to gather Nether-specific resources, but be prepared for a fight.</p>\n</li>\n<li>\n<p><strong>End World (5k x 5k)</strong>\nHome of the Ender Dragon. Venture here to challenge the boss, find Elytras, and explore End Cities.</p>\n</li>\n<li>\n<p><strong>Mining World (5k x 5k)</strong>\nThis world is specifically for gathering resources! It resets on a regular schedule, so it's always full of fresh ores and materials. Using the Mining World helps keep our main Survival World beautiful and unspoiled.</p>\n</li>\n</ul>\n",
    "data": "title:\"Worlds\" description:\"Explore the different worlds our server has to offer. Each one has a unique purpose and size.\""
  }
]

export function getAllGuides(): GuideItem[] {
  return STATIC_GUIDES
}

export function getGuideBySlug(slug: string): GuideItem | undefined {
  return STATIC_GUIDES.find(guide => guide.slug === slug)
}

export async function getMarkdownContent(slug: string): Promise<MarkdownContent> {
  const guide = getGuideBySlug(slug)
  if (!guide) {
    throw new Error(`Guide not found: ${slug}`)
  }
  
  return {
    content: guide.content,
    data: guide.data
  }
}
